services:
  db:
    image: mariadb
    container_name: mariaDB
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    container_name: adminer-ui
    ports:
      - "8080:8080"
    restart: always

volumes:
  db_data:
